steps:
  # Build MCP Server Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'build'
      - '-t'
      - 'gcr.io/$PROJECT_ID/twinmcp-mcp-server:$COMMIT_SHA'
      - '-t'
      - 'gcr.io/$PROJECT_ID/twinmcp-mcp-server:latest'
      - '-f'
      - 'packages/mcp-server/Dockerfile'
      - 'packages/mcp-server'

  # Push to Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/twinmcp-mcp-server:$COMMIT_SHA'

  - name: 'gcr.io/cloud-builders/docker'
    args:
      - 'push'
      - 'gcr.io/$PROJECT_ID/twinmcp-mcp-server:latest'

  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'twinmcp-mcp-server'
      - '--image'
      - 'gcr.io/$PROJECT_ID/twinmcp-mcp-server:$COMMIT_SHA'
      - '--region'
      - '${_REGION}'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated'
      - '--port'
      - '3001'
      - '--set-env-vars'
      - 'TWINMCP_PORT=3001,TWINMCP_HOST=0.0.0.0,TWINMCP_API_BASE_URL=${_API_BASE_URL},TWINMCP_CORS_ORIGINS=*'
      - '--memory'
      - '512Mi'
      - '--cpu'
      - '1'
      - '--min-instances'
      - '0'
      - '--max-instances'
      - '10'

substitutions:
  _REGION: europe-west1
  _API_BASE_URL: https://your-saas-domain.com

images:
  - 'gcr.io/$PROJECT_ID/twinmcp-mcp-server:$COMMIT_SHA'
  - 'gcr.io/$PROJECT_ID/twinmcp-mcp-server:latest'

options:
  logging: CLOUD_LOGGING_ONLY
