/**
 * MCP Tools Catalog — Single source of truth for all available MCP tools.
 * Each tool maps to a real MCP server that Pro users can activate.
 */

// ─── Types ──────────────────────────────────────────────────────

export type McpToolCategory =
  | 'search'
  | 'development'
  | 'database'
  | 'cloud'
  | 'productivity'
  | 'ai'
  | 'monitoring'
  | 'data';

export interface McpToolDefinition {
  id: string;
  name: string;
  slug: string;
  provider: string;
  description: string;
  category: McpToolCategory;
  iconUrl: string | null;
  docsUrl: string;
  requiresApiKey: boolean;
  envKeyName: string | null;
  tags: string[];
  popular: boolean;
}

// ─── Category Metadata ──────────────────────────────────────────

export const TOOL_CATEGORIES: Record<McpToolCategory, { label: string; description: string; emoji: string }> = {
  search:       { label: 'Recherche',     description: 'Moteurs de recherche et extraction de données',      emoji: '🔍' },
  development:  { label: 'Développement', description: 'Outils de code, CI/CD et gestion de projet',        emoji: '💻' },
  database:     { label: 'Bases de données', description: 'Connecteurs vers bases SQL, NoSQL et graphe',     emoji: '🗄️' },
  cloud:        { label: 'Cloud & Infra',  description: 'AWS, Azure, Docker et orchestration',               emoji: '☁️' },
  productivity: { label: 'Productivité',   description: 'Notion, Airtable et outils de gestion',             emoji: '📋' },
  ai:           { label: 'IA & ML',        description: 'Modèles IA, agents et services cognitifs',          emoji: '🤖' },
  monitoring:   { label: 'Monitoring',     description: 'Observabilité, dashboards et alerting',              emoji: '📊' },
  data:         { label: 'Données',        description: 'Analyse, scraping et traitement de données',         emoji: '📈' },
};

// ─── Tool Catalog ───────────────────────────────────────────────

export const MCP_TOOLS_CATALOG: McpToolDefinition[] = [
  // ── Search ────────────────────────────────────────────────────
  {
    id: 'brave-search',
    name: 'Brave Search',
    slug: 'brave-search',
    provider: 'Brave',
    description: 'Recherche Web (pages, images, news, vidéos) via l\'API Brave Search.',
    category: 'search',
    iconUrl: null,
    docsUrl: 'https://github.com/brave/brave-search-mcp',
    requiresApiKey: true,
    envKeyName: 'BRAVE_SEARCH_API_KEY',
    tags: ['search', 'web', 'news', 'images'],
    popular: true,
  },
  {
    id: 'perplexity',
    name: 'Perplexity',
    slug: 'perplexity',
    provider: 'Perplexity AI',
    description: 'Recherche web temps réel via l\'API Perplexity pour des réponses sourcées.',
    category: 'search',
    iconUrl: null,
    docsUrl: 'https://github.com/perplexityai/perplexity-mcp',
    requiresApiKey: true,
    envKeyName: 'PERPLEXITY_API_KEY',
    tags: ['search', 'ai', 'real-time'],
    popular: true,
  },
  {
    id: 'arxiv',
    name: 'ArXiv',
    slug: 'arxiv',
    provider: 'jasonleinart',
    description: 'Accès et gestion locale de papiers arXiv, avec outils de recherche et d\'analyse.',
    category: 'search',
    iconUrl: null,
    docsUrl: 'https://github.com/jasonleinart/arxiv-mcp',
    requiresApiKey: false,
    envKeyName: null,
    tags: ['research', 'papers', 'science'],
    popular: false,
  },

  // ── Development ───────────────────────────────────────────────
  {
    id: 'github',
    name: 'GitHub',
    slug: 'github',
    provider: 'GitHub',
    description: 'Intégration officielle GitHub : repos, issues, PRs, actions et API avancée.',
    category: 'development',
    iconUrl: null,
    docsUrl: 'https://github.com/github/github-mcp-server',
    requiresApiKey: true,
    envKeyName: 'GITHUB_TOKEN',
    tags: ['git', 'code', 'ci-cd', 'issues'],
    popular: true,
  },
  {
    id: 'playwright',
    name: 'Playwright',
    slug: 'playwright',
    provider: 'Microsoft',
    description: 'Automatisation de navigateur, tests E2E et scraping via Playwright.',
    category: 'development',
    iconUrl: null,
    docsUrl: 'https://github.com/microsoft/playwright-mcp',
    requiresApiKey: false,
    envKeyName: null,
    tags: ['browser', 'testing', 'automation', 'scraping'],
    popular: true,
  },
  {
    id: 'desktop-commander',
    name: 'Desktop Commander',
    slug: 'desktop-commander',
    provider: 'wonderwhy-er',
    description: 'Recherche, mise à jour, gestion de fichiers et exécution de commandes terminal.',
    category: 'development',
    iconUrl: null,
    docsUrl: 'https://github.com/wonderwhy-er/desktop-commander-mcp',
    requiresApiKey: false,
    envKeyName: null,
    tags: ['terminal', 'files', 'commands'],
    popular: false,
  },
  {
    id: 'context7',
    name: 'Context7',
    slug: 'context7',
    provider: 'Upstash',
    description: 'Documentation de code à jour pour LLMs et éditeurs de code IA.',
    category: 'development',
    iconUrl: null,
    docsUrl: 'https://github.com/upstash/context7',
    requiresApiKey: false,
    envKeyName: null,
    tags: ['docs', 'code', 'llm', 'context'],
    popular: true,
  },
  {
    id: 'docker-hub',
    name: 'Docker Hub',
    slug: 'docker-hub',
    provider: 'Docker',
    description: 'Serveur MCP officiel Docker Hub pour gérer images et conteneurs.',
    category: 'development',
    iconUrl: null,
    docsUrl: 'https://github.com/docker/docker-mcp',
    requiresApiKey: true,
    envKeyName: 'DOCKER_HUB_TOKEN',
    tags: ['docker', 'containers', 'images'],
    popular: false,
  },
  {
    id: 'arm',
    name: 'Arm',
    slug: 'arm',
    provider: 'Arm',
    description: 'Outils spécialisés pour développement et optimisation sur architecture Arm.',
    category: 'development',
    iconUrl: null,
    docsUrl: 'https://github.com/arm/arm-mcp',
    requiresApiKey: false,
    envKeyName: null,
    tags: ['arm', 'architecture', 'optimization'],
    popular: false,
  },

  // ── Database ──────────────────────────────────────────────────
  {
    id: 'mongodb',
    name: 'MongoDB',
    slug: 'mongodb',
    provider: 'MongoDB',
    description: 'Connexion aux bases MongoDB et clusters MongoDB Atlas.',
    category: 'database',
    iconUrl: null,
    docsUrl: 'https://github.com/mongodb-js/mongodb-mcp',
    requiresApiKey: true,
    envKeyName: 'MONGODB_URI',
    tags: ['nosql', 'document', 'atlas'],
    popular: true,
  },
  {
    id: 'couchbase',
    name: 'Couchbase',
    slug: 'couchbase',
    provider: 'Couchbase Ecosystem',
    description: 'Base de données document distribuée avec moteur de recherche et capacités analytiques.',
    category: 'database',
    iconUrl: null,
    docsUrl: 'https://github.com/Couchbase-Ecosystem/couchbase-mcp',
    requiresApiKey: true,
    envKeyName: 'COUCHBASE_CONNECTION_STRING',
    tags: ['nosql', 'document', 'search', 'analytics'],
    popular: false,
  },
  {
    id: 'elasticsearch',
    name: 'Elasticsearch',
    slug: 'elasticsearch',
    provider: 'Elastic',
    description: 'Interaction en langage naturel avec vos index Elasticsearch.',
    category: 'database',
    iconUrl: null,
    docsUrl: 'https://github.com/elastic/elasticsearch-mcp',
    requiresApiKey: true,
    envKeyName: 'ELASTICSEARCH_URL',
    tags: ['search', 'analytics', 'logs'],
    popular: true,
  },
  {
    id: 'neon',
    name: 'Neon',
    slug: 'neon',
    provider: 'Neon Database',
    description: 'Interaction avec l\'API de gestion Neon et les bases PostgreSQL serverless.',
    category: 'database',
    iconUrl: null,
    docsUrl: 'https://github.com/neondatabase/neon-mcp',
    requiresApiKey: true,
    envKeyName: 'NEON_API_KEY',
    tags: ['postgres', 'serverless', 'sql'],
    popular: false,
  },
  {
    id: 'amazon-neptune',
    name: 'Amazon Neptune',
    slug: 'amazon-neptune',
    provider: 'AWS',
    description: 'Requêtes sur base graphe avec Cypher et Gremlin.',
    category: 'database',
    iconUrl: null,
    docsUrl: 'https://github.com/awslabs/amazon-neptune-mcp',
    requiresApiKey: true,
    envKeyName: 'NEPTUNE_ENDPOINT',
    tags: ['graph', 'cypher', 'gremlin', 'aws'],
    popular: false,
  },

  // ── Cloud & Infra ─────────────────────────────────────────────
  {
    id: 'aws-core',
    name: 'AWS Core',
    slug: 'aws-core',
    provider: 'AWS Labs',
    description: 'Point de départ pour utiliser les serveurs MCP AWS — S3, Lambda, EC2 et plus.',
    category: 'cloud',
    iconUrl: null,
    docsUrl: 'https://github.com/awslabs/aws-mcp',
    requiresApiKey: true,
    envKeyName: 'AWS_ACCESS_KEY_ID',
    tags: ['aws', 's3', 'lambda', 'ec2'],
    popular: true,
  },
  {
    id: 'azure-aks',
    name: 'Azure Kubernetes (AKS)',
    slug: 'azure-aks',
    provider: 'Microsoft Azure',
    description: 'Serveur MCP officiel Azure Kubernetes Service.',
    category: 'cloud',
    iconUrl: null,
    docsUrl: 'https://github.com/Azure/aks-mcp',
    requiresApiKey: true,
    envKeyName: 'AZURE_SUBSCRIPTION_ID',
    tags: ['azure', 'kubernetes', 'containers'],
    popular: false,
  },
  {
    id: 'heroku',
    name: 'Heroku',
    slug: 'heroku',
    provider: 'Heroku',
    description: 'Serveur MCP Heroku basé sur le CLI Heroku pour gérer apps et dynos.',
    category: 'cloud',
    iconUrl: null,
    docsUrl: 'https://github.com/heroku/heroku-mcp',
    requiresApiKey: true,
    envKeyName: 'HEROKU_API_KEY',
    tags: ['paas', 'deploy', 'dynos'],
    popular: false,
  },
  {
    id: 'aws-bedrock',
    name: 'AWS Bedrock AgentCore',
    slug: 'aws-bedrock',
    provider: 'AWS',
    description: 'Documentation et services de la plateforme AgentCore pour agents IA.',
    category: 'cloud',
    iconUrl: null,
    docsUrl: 'https://github.com/awslabs/aws-bedrock-mcp',
    requiresApiKey: true,
    envKeyName: 'AWS_ACCESS_KEY_ID',
    tags: ['aws', 'ai', 'agents', 'bedrock'],
    popular: false,
  },

  // ── Productivity ──────────────────────────────────────────────
  {
    id: 'notion',
    name: 'Notion',
    slug: 'notion',
    provider: 'Notion',
    description: 'Serveur MCP officiel Notion pour accéder et manipuler vos pages et bases.',
    category: 'productivity',
    iconUrl: null,
    docsUrl: 'https://github.com/makenotion/notion-mcp',
    requiresApiKey: true,
    envKeyName: 'NOTION_API_KEY',
    tags: ['notes', 'wiki', 'project-management'],
    popular: true,
  },
  {
    id: 'airtable',
    name: 'Airtable',
    slug: 'airtable',
    provider: 'domdomegg',
    description: 'Accès direct aux bases Airtable (schemas, requêtes, enregistrements) pour automatiser des workflows.',
    category: 'productivity',
    iconUrl: null,
    docsUrl: 'https://github.com/domdomegg/airtable-mcp',
    requiresApiKey: true,
    envKeyName: 'AIRTABLE_API_KEY',
    tags: ['spreadsheet', 'automation', 'workflows'],
    popular: false,
  },
  {
    id: 'stripe',
    name: 'Stripe',
    slug: 'stripe',
    provider: 'Stripe',
    description: 'Interaction avec les services Stripe : paiements, abonnements, factures.',
    category: 'productivity',
    iconUrl: null,
    docsUrl: 'https://github.com/stripe/stripe-mcp',
    requiresApiKey: true,
    envKeyName: 'STRIPE_MCP_API_KEY',
    tags: ['payments', 'billing', 'subscriptions'],
    popular: true,
  },

  // ── AI & ML ───────────────────────────────────────────────────
  {
    id: 'amazon-kendra',
    name: 'Amazon Kendra Index',
    slug: 'amazon-kendra',
    provider: 'AWS',
    description: 'Recherche d\'entreprise et amélioration RAG via Amazon Kendra.',
    category: 'ai',
    iconUrl: null,
    docsUrl: 'https://github.com/awslabs/amazon-kendra-mcp',
    requiresApiKey: true,
    envKeyName: 'AWS_ACCESS_KEY_ID',
    tags: ['search', 'rag', 'enterprise', 'aws'],
    popular: false,
  },
  {
    id: 'amazon-q-business',
    name: 'Amazon Q Business',
    slug: 'amazon-q-business',
    provider: 'AWS',
    description: 'Assistant IA pour contenu ingéré avec accès anonyme.',
    category: 'ai',
    iconUrl: null,
    docsUrl: 'https://github.com/awslabs/amazon-q-business-mcp',
    requiresApiKey: true,
    envKeyName: 'AWS_ACCESS_KEY_ID',
    tags: ['ai', 'assistant', 'enterprise', 'aws'],
    popular: false,
  },

  // ── Monitoring ────────────────────────────────────────────────
  {
    id: 'grafana',
    name: 'Grafana',
    slug: 'grafana',
    provider: 'Grafana',
    description: 'Serveur MCP Grafana pour dashboards, alertes et observabilité.',
    category: 'monitoring',
    iconUrl: null,
    docsUrl: 'https://github.com/grafana/grafana-mcp',
    requiresApiKey: true,
    envKeyName: 'GRAFANA_API_KEY',
    tags: ['dashboards', 'alerts', 'observability'],
    popular: true,
  },

  // ── Data ──────────────────────────────────────────────────────
  {
    id: 'apify',
    name: 'Apify',
    slug: 'apify',
    provider: 'Apify',
    description: 'Outils Apify pour scraping, extraction et automatisation web à grande échelle.',
    category: 'data',
    iconUrl: null,
    docsUrl: 'https://github.com/apify/apify-mcp',
    requiresApiKey: true,
    envKeyName: 'APIFY_API_KEY',
    tags: ['scraping', 'extraction', 'automation'],
    popular: false,
  },
  {
    id: 'ais-fleet',
    name: 'AIS Fleet',
    slug: 'ais-fleet',
    provider: 'AIS Fleet',
    description: 'Analyse et requêtes sur les données AIS de trafic maritime.',
    category: 'data',
    iconUrl: null,
    docsUrl: 'https://github.com/ais-fleet/ais-fleet-mcp',
    requiresApiKey: true,
    envKeyName: 'AIS_FLEET_API_KEY',
    tags: ['maritime', 'tracking', 'geospatial'],
    popular: false,
  },

  // ── Communication ─────────────────────────────────────────────
  {
    id: 'slack',
    name: 'Slack',
    slug: 'slack',
    provider: 'Model Context Protocol',
    description: 'Envoyer des messages, gérer des canaux et rechercher dans l\'historique Slack.',
    category: 'productivity',
    iconUrl: null,
    docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/slack',
    requiresApiKey: true,
    envKeyName: 'SLACK_BOT_TOKEN',
    tags: ['messaging', 'team', 'channels', 'notifications'],
    popular: true,
  },

  // ── Geolocation ───────────────────────────────────────────────
  {
    id: 'google-maps',
    name: 'Google Maps',
    slug: 'google-maps',
    provider: 'Model Context Protocol',
    description: 'Géocodage, itinéraires, recherche de lieux et calcul de distances via Google Maps Platform.',
    category: 'data',
    iconUrl: null,
    docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/google-maps',
    requiresApiKey: true,
    envKeyName: 'GOOGLE_MAPS_API_KEY',
    tags: ['maps', 'geocoding', 'directions', 'places'],
    popular: true,
  },

  // ── Error Monitoring ──────────────────────────────────────────
  {
    id: 'sentry',
    name: 'Sentry',
    slug: 'sentry',
    provider: 'Sentry',
    description: 'Monitoring d\'erreurs en production : issues, stacktraces, releases et performance.',
    category: 'monitoring',
    iconUrl: null,
    docsUrl: 'https://github.com/getsentry/sentry-mcp',
    requiresApiKey: true,
    envKeyName: 'SENTRY_AUTH_TOKEN',
    tags: ['errors', 'monitoring', 'stacktrace', 'releases'],
    popular: true,
  },

  // ── Edge Computing ────────────────────────────────────────────
  {
    id: 'cloudflare',
    name: 'Cloudflare',
    slug: 'cloudflare',
    provider: 'Cloudflare',
    description: 'Gérer Workers, KV, R2, D1 et les configurations DNS via l\'API Cloudflare.',
    category: 'cloud',
    iconUrl: null,
    docsUrl: 'https://github.com/cloudflare/mcp-server-cloudflare',
    requiresApiKey: true,
    envKeyName: 'CLOUDFLARE_API_TOKEN',
    tags: ['cdn', 'workers', 'edge', 'dns', 'r2'],
    popular: true,
  },

  // ── Backend as a Service ──────────────────────────────────────
  {
    id: 'supabase',
    name: 'Supabase',
    slug: 'supabase',
    provider: 'Supabase',
    description: 'Gestion de bases PostgreSQL, auth, storage et fonctions edge Supabase.',
    category: 'database',
    iconUrl: null,
    docsUrl: 'https://github.com/supabase/supabase-mcp',
    requiresApiKey: true,
    envKeyName: 'SUPABASE_ACCESS_TOKEN',
    tags: ['postgres', 'auth', 'storage', 'baas'],
    popular: true,
  },
  {
    id: 'firebase',
    name: 'Firebase',
    slug: 'firebase',
    provider: 'gannonh',
    description: 'Interaction avec Firestore, Auth, Storage et Realtime Database de Firebase.',
    category: 'database',
    iconUrl: null,
    docsUrl: 'https://github.com/gannonh/firebase-mcp',
    requiresApiKey: true,
    envKeyName: 'FIREBASE_SERVICE_ACCOUNT_KEY',
    tags: ['firestore', 'auth', 'storage', 'google'],
    popular: false,
  },

  // ── Project Management ────────────────────────────────────────
  {
    id: 'linear',
    name: 'Linear',
    slug: 'linear',
    provider: 'jerhadf',
    description: 'Gestion d\'issues, projets et cycles Linear pour le suivi de développement.',
    category: 'productivity',
    iconUrl: null,
    docsUrl: 'https://github.com/jerhadf/linear-mcp-server',
    requiresApiKey: true,
    envKeyName: 'LINEAR_API_KEY',
    tags: ['issues', 'project-management', 'sprints', 'tickets'],
    popular: false,
  },

  // ── Design ────────────────────────────────────────────────────
  {
    id: 'figma',
    name: 'Figma',
    slug: 'figma',
    provider: 'Figma',
    description: 'Lecture de fichiers Figma, extraction de composants, styles et métadonnées de design.',
    category: 'productivity',
    iconUrl: null,
    docsUrl: 'https://github.com/figma/figma-mcp',
    requiresApiKey: true,
    envKeyName: 'FIGMA_ACCESS_TOKEN',
    tags: ['design', 'ui', 'components', 'prototyping'],
    popular: true,
  },

  // ── Deployment ────────────────────────────────────────────────
  {
    id: 'vercel',
    name: 'Vercel',
    slug: 'vercel',
    provider: 'Vercel',
    description: 'Gérer les déploiements, projets, domaines et variables d\'environnement Vercel.',
    category: 'cloud',
    iconUrl: null,
    docsUrl: 'https://github.com/vercel/vercel-mcp',
    requiresApiKey: true,
    envKeyName: 'VERCEL_TOKEN',
    tags: ['deploy', 'serverless', 'frontend', 'nextjs'],
    popular: true,
  },

  // ── API Testing ───────────────────────────────────────────────
  {
    id: 'postman',
    name: 'Postman',
    slug: 'postman',
    provider: 'Postman Labs',
    description: 'Exécuter des collections Postman, gérer des environnements et tester des APIs.',
    category: 'development',
    iconUrl: null,
    docsUrl: 'https://github.com/postmanlabs/postman-mcp-server',
    requiresApiKey: true,
    envKeyName: 'POSTMAN_API_KEY',
    tags: ['api', 'testing', 'collections', 'http'],
    popular: false,
  },

  // ── Cache & Key-Value ─────────────────────────────────────────
  {
    id: 'redis',
    name: 'Redis',
    slug: 'redis',
    provider: 'Model Context Protocol',
    description: 'Interaction avec Redis : opérations clé-valeur, pub/sub, streams et gestion de cache.',
    category: 'database',
    iconUrl: null,
    docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/redis',
    requiresApiKey: true,
    envKeyName: 'REDIS_URL',
    tags: ['cache', 'key-value', 'pub-sub', 'streams'],
    popular: true,
  },

  // ── ORM ───────────────────────────────────────────────────────
  {
    id: 'prisma',
    name: 'Prisma',
    slug: 'prisma',
    provider: 'Prisma',
    description: 'Introspection de schémas, génération de requêtes et gestion de migrations Prisma.',
    category: 'database',
    iconUrl: null,
    docsUrl: 'https://github.com/prisma/prisma-mcp',
    requiresApiKey: true,
    envKeyName: 'DATABASE_URL',
    tags: ['orm', 'postgres', 'mysql', 'migrations', 'schema'],
    popular: true,
  },

  // ── Communication ─────────────────────────────────────────────
  {
    id: 'twilio',
    name: 'Twilio',
    slug: 'twilio',
    provider: 'Twilio',
    description: 'Envoi de SMS, appels vocaux, vérification et gestion de numéros via l\'API Twilio.',
    category: 'productivity',
    iconUrl: null,
    docsUrl: 'https://github.com/twilio/twilio-mcp',
    requiresApiKey: true,
    envKeyName: 'TWILIO_AUTH_TOKEN',
    tags: ['sms', 'voice', 'verification', 'messaging'],
    popular: false,
  },

  // ── Project Management (Atlassian) ────────────────────────────
  {
    id: 'jira',
    name: 'Jira',
    slug: 'jira',
    provider: 'Atlassian',
    description: 'Gestion d\'issues, sprints, boards et workflows Jira pour le suivi de projet.',
    category: 'productivity',
    iconUrl: null,
    docsUrl: 'https://github.com/atlassian/jira-mcp',
    requiresApiKey: true,
    envKeyName: 'JIRA_API_TOKEN',
    tags: ['issues', 'sprints', 'agile', 'project-management'],
    popular: true,
  },
  {
    id: 'confluence',
    name: 'Confluence',
    slug: 'confluence',
    provider: 'Atlassian',
    description: 'Recherche, lecture et création de pages dans l\'espace de documentation Confluence.',
    category: 'productivity',
    iconUrl: null,
    docsUrl: 'https://github.com/atlassian/confluence-mcp',
    requiresApiKey: true,
    envKeyName: 'CONFLUENCE_API_TOKEN',
    tags: ['wiki', 'documentation', 'knowledge-base'],
    popular: false,
  },

  // ── Observability ─────────────────────────────────────────────
  {
    id: 'datadog',
    name: 'Datadog',
    slug: 'datadog',
    provider: 'Datadog',
    description: 'Métriques, logs, traces et dashboards Datadog pour l\'observabilité full-stack.',
    category: 'monitoring',
    iconUrl: null,
    docsUrl: 'https://github.com/DataDog/datadog-mcp',
    requiresApiKey: true,
    envKeyName: 'DATADOG_API_KEY',
    tags: ['metrics', 'logs', 'traces', 'apm', 'dashboards'],
    popular: true,
  },
  {
    id: 'pagerduty',
    name: 'PagerDuty',
    slug: 'pagerduty',
    provider: 'PagerDuty',
    description: 'Gestion des incidents, on-call schedules et escalation policies PagerDuty.',
    category: 'monitoring',
    iconUrl: null,
    docsUrl: 'https://github.com/PagerDuty/pagerduty-mcp',
    requiresApiKey: true,
    envKeyName: 'PAGERDUTY_API_KEY',
    tags: ['incidents', 'on-call', 'alerting', 'escalation'],
    popular: false,
  },

  // ── Vector Databases ──────────────────────────────────────────
  {
    id: 'pinecone',
    name: 'Pinecone',
    slug: 'pinecone',
    provider: 'Pinecone',
    description: 'Base vectorielle pour recherche sémantique, RAG et embeddings à grande échelle.',
    category: 'ai',
    iconUrl: null,
    docsUrl: 'https://github.com/pinecone-io/pinecone-mcp',
    requiresApiKey: true,
    envKeyName: 'PINECONE_API_KEY',
    tags: ['vectors', 'embeddings', 'rag', 'semantic-search'],
    popular: true,
  },
  {
    id: 'turbopuffer',
    name: 'Turbopuffer',
    slug: 'turbopuffer',
    provider: 'Turbopuffer',
    description: 'Base vectorielle ultra-rapide pour la recherche de similarité et le filtrage hybride.',
    category: 'ai',
    iconUrl: null,
    docsUrl: 'https://github.com/turbopuffer/turbopuffer-mcp',
    requiresApiKey: true,
    envKeyName: 'TURBOPUFFER_API_KEY',
    tags: ['vectors', 'similarity', 'hybrid-search', 'fast'],
    popular: false,
  },

  // ── Git Platforms ─────────────────────────────────────────────
  {
    id: 'gitlab',
    name: 'GitLab',
    slug: 'gitlab',
    provider: 'GitLab',
    description: 'Gestion de repos, merge requests, pipelines CI/CD et issues GitLab.',
    category: 'development',
    iconUrl: null,
    docsUrl: 'https://github.com/gitlab/gitlab-mcp',
    requiresApiKey: true,
    envKeyName: 'GITLAB_TOKEN',
    tags: ['git', 'ci-cd', 'merge-requests', 'pipelines'],
    popular: true,
  },

  // ── E-commerce ────────────────────────────────────────────────
  {
    id: 'shopify',
    name: 'Shopify',
    slug: 'shopify',
    provider: 'Shopify',
    description: 'Gestion de produits, commandes, clients et inventaire via l\'API Shopify.',
    category: 'productivity',
    iconUrl: null,
    docsUrl: 'https://github.com/Shopify/shopify-mcp',
    requiresApiKey: true,
    envKeyName: 'SHOPIFY_ACCESS_TOKEN',
    tags: ['ecommerce', 'products', 'orders', 'inventory'],
    popular: true,
  },

  // ── Data Warehouses ───────────────────────────────────────────
  {
    id: 'snowflake',
    name: 'Snowflake',
    slug: 'snowflake',
    provider: 'Snowflake',
    description: 'Requêtes SQL, gestion de warehouses et exploration de données Snowflake.',
    category: 'data',
    iconUrl: null,
    docsUrl: 'https://github.com/Snowflake-Labs/snowflake-mcp',
    requiresApiKey: true,
    envKeyName: 'SNOWFLAKE_ACCOUNT',
    tags: ['sql', 'warehouse', 'analytics', 'data-lake'],
    popular: true,
  },
  {
    id: 'bigquery',
    name: 'Google BigQuery',
    slug: 'bigquery',
    provider: 'Google Cloud',
    description: 'Requêtes analytiques à grande échelle, datasets et tables BigQuery.',
    category: 'data',
    iconUrl: null,
    docsUrl: 'https://github.com/google-cloud/bigquery-mcp',
    requiresApiKey: true,
    envKeyName: 'GOOGLE_APPLICATION_CREDENTIALS',
    tags: ['sql', 'analytics', 'big-data', 'google-cloud'],
    popular: true,
  },

  // ── Community & Chat ──────────────────────────────────────────
  {
    id: 'discord',
    name: 'Discord',
    slug: 'discord',
    provider: 'Discord',
    description: 'Gestion de serveurs, canaux, messages et membres Discord via bot API.',
    category: 'productivity',
    iconUrl: null,
    docsUrl: 'https://github.com/discord/discord-mcp',
    requiresApiKey: true,
    envKeyName: 'DISCORD_BOT_TOKEN',
    tags: ['chat', 'community', 'bots', 'servers'],
    popular: true,
  },

  // ── Infrastructure as Code ────────────────────────────────────
  {
    id: 'terraform',
    name: 'Terraform',
    slug: 'terraform',
    provider: 'HashiCorp',
    description: 'Gestion d\'infrastructure as code : plans, apply, state et modules Terraform.',
    category: 'cloud',
    iconUrl: null,
    docsUrl: 'https://github.com/hashicorp/terraform-mcp',
    requiresApiKey: true,
    envKeyName: 'TF_API_TOKEN',
    tags: ['iac', 'infrastructure', 'provisioning', 'hcl'],
    popular: true,
  },
  {
    id: 'kubernetes',
    name: 'Kubernetes',
    slug: 'kubernetes',
    provider: 'Model Context Protocol',
    description: 'Gestion de clusters, pods, deployments et services Kubernetes.',
    category: 'cloud',
    iconUrl: null,
    docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/kubernetes',
    requiresApiKey: true,
    envKeyName: 'KUBECONFIG',
    tags: ['k8s', 'containers', 'orchestration', 'pods'],
    popular: true,
  },

  // ── Email ─────────────────────────────────────────────────────
  {
    id: 'sendgrid',
    name: 'SendGrid',
    slug: 'sendgrid',
    provider: 'Twilio SendGrid',
    description: 'Envoi d\'emails transactionnels et marketing, gestion de templates et statistiques.',
    category: 'productivity',
    iconUrl: null,
    docsUrl: 'https://github.com/sendgrid/sendgrid-mcp',
    requiresApiKey: true,
    envKeyName: 'SENDGRID_API_KEY',
    tags: ['email', 'transactional', 'marketing', 'templates'],
    popular: false,
  },

  // ── CRM ───────────────────────────────────────────────────────
  {
    id: 'hubspot',
    name: 'HubSpot',
    slug: 'hubspot',
    provider: 'HubSpot',
    description: 'Gestion de contacts, deals, tickets et pipelines CRM HubSpot.',
    category: 'productivity',
    iconUrl: null,
    docsUrl: 'https://github.com/HubSpot/hubspot-mcp',
    requiresApiKey: true,
    envKeyName: 'HUBSPOT_ACCESS_TOKEN',
    tags: ['crm', 'contacts', 'deals', 'marketing'],
    popular: true,
  },

  // ── Support ───────────────────────────────────────────────────
  {
    id: 'zendesk',
    name: 'Zendesk',
    slug: 'zendesk',
    provider: 'Zendesk',
    description: 'Gestion de tickets, agents, macros et satisfaction client Zendesk.',
    category: 'productivity',
    iconUrl: null,
    docsUrl: 'https://github.com/zendesk/zendesk-mcp',
    requiresApiKey: true,
    envKeyName: 'ZENDESK_API_TOKEN',
    tags: ['support', 'tickets', 'helpdesk', 'customer-service'],
    popular: false,
  },

  // ── Task Management ───────────────────────────────────────────
  {
    id: 'asana',
    name: 'Asana',
    slug: 'asana',
    provider: 'Asana',
    description: 'Gestion de tâches, projets, portfolios et timelines Asana.',
    category: 'productivity',
    iconUrl: null,
    docsUrl: 'https://github.com/asana/asana-mcp',
    requiresApiKey: true,
    envKeyName: 'ASANA_ACCESS_TOKEN',
    tags: ['tasks', 'projects', 'portfolios', 'workflows'],
    popular: false,
  },

  // ── LLM Providers ────────────────────────────────────────────
  {
    id: 'openai',
    name: 'OpenAI',
    slug: 'openai',
    provider: 'OpenAI',
    description: 'Accès aux modèles GPT, DALL·E, Whisper et assistants via l\'API OpenAI.',
    category: 'ai',
    iconUrl: null,
    docsUrl: 'https://github.com/openai/openai-mcp',
    requiresApiKey: true,
    envKeyName: 'OPENAI_API_KEY',
    tags: ['llm', 'gpt', 'dall-e', 'whisper', 'assistants'],
    popular: true,
  },
  {
    id: 'anthropic',
    name: 'Anthropic',
    slug: 'anthropic',
    provider: 'Anthropic',
    description: 'Accès aux modèles Claude pour la génération de texte, analyse et raisonnement.',
    category: 'ai',
    iconUrl: null,
    docsUrl: 'https://github.com/anthropics/anthropic-mcp',
    requiresApiKey: true,
    envKeyName: 'ANTHROPIC_API_KEY',
    tags: ['llm', 'claude', 'reasoning', 'analysis'],
    popular: true,
  },
  {
    id: 'huggingface',
    name: 'Hugging Face',
    slug: 'huggingface',
    provider: 'Hugging Face',
    description: 'Accès aux modèles, datasets et espaces Hugging Face Hub.',
    category: 'ai',
    iconUrl: null,
    docsUrl: 'https://github.com/huggingface/huggingface-mcp',
    requiresApiKey: true,
    envKeyName: 'HF_TOKEN',
    tags: ['models', 'datasets', 'transformers', 'inference'],
    popular: true,
  },
  {
    id: 'weaviate',
    name: 'Weaviate',
    slug: 'weaviate',
    provider: 'Weaviate',
    description: 'Base vectorielle open-source pour la recherche sémantique et le RAG.',
    category: 'ai',
    iconUrl: null,
    docsUrl: 'https://github.com/weaviate/weaviate-mcp',
    requiresApiKey: true,
    envKeyName: 'WEAVIATE_API_KEY',
    tags: ['vectors', 'semantic-search', 'rag', 'open-source'],
    popular: false,
  },

  // ── Git & CI/CD ───────────────────────────────────────────────
  {
    id: 'bitbucket',
    name: 'Bitbucket',
    slug: 'bitbucket',
    provider: 'Atlassian',
    description: 'Gestion de repos, pull requests, pipelines et snippets Bitbucket.',
    category: 'development',
    iconUrl: null,
    docsUrl: 'https://github.com/atlassian/bitbucket-mcp',
    requiresApiKey: true,
    envKeyName: 'BITBUCKET_APP_PASSWORD',
    tags: ['git', 'pull-requests', 'pipelines', 'atlassian'],
    popular: false,
  },
  {
    id: 'circleci',
    name: 'CircleCI',
    slug: 'circleci',
    provider: 'CircleCI',
    description: 'Gestion de pipelines CI/CD, jobs, workflows et orbs CircleCI.',
    category: 'development',
    iconUrl: null,
    docsUrl: 'https://github.com/CircleCI-Public/circleci-mcp',
    requiresApiKey: true,
    envKeyName: 'CIRCLECI_TOKEN',
    tags: ['ci-cd', 'pipelines', 'builds', 'workflows'],
    popular: false,
  },
  {
    id: 'npm',
    name: 'npm',
    slug: 'npm',
    provider: 'npm',
    description: 'Recherche de packages, versions, dépendances et audit de sécurité npm.',
    category: 'development',
    iconUrl: null,
    docsUrl: 'https://github.com/npm/npm-mcp',
    requiresApiKey: false,
    envKeyName: null,
    tags: ['packages', 'dependencies', 'registry', 'security'],
    popular: true,
  },

  // ── NoSQL & Analytics DBs ─────────────────────────────────────
  {
    id: 'dynamodb',
    name: 'Amazon DynamoDB',
    slug: 'dynamodb',
    provider: 'AWS',
    description: 'Opérations CRUD, requêtes et scans sur tables DynamoDB.',
    category: 'database',
    iconUrl: null,
    docsUrl: 'https://github.com/awslabs/dynamodb-mcp',
    requiresApiKey: true,
    envKeyName: 'AWS_ACCESS_KEY_ID',
    tags: ['nosql', 'key-value', 'serverless', 'aws'],
    popular: true,
  },
  {
    id: 'cockroachdb',
    name: 'CockroachDB',
    slug: 'cockroachdb',
    provider: 'Cockroach Labs',
    description: 'Base SQL distribuée et résiliente, compatible PostgreSQL.',
    category: 'database',
    iconUrl: null,
    docsUrl: 'https://github.com/cockroachdb/cockroachdb-mcp',
    requiresApiKey: true,
    envKeyName: 'COCKROACH_URL',
    tags: ['sql', 'distributed', 'postgres-compatible', 'resilient'],
    popular: false,
  },
  {
    id: 'clickhouse',
    name: 'ClickHouse',
    slug: 'clickhouse',
    provider: 'ClickHouse',
    description: 'Base analytique colonnaire ultra-rapide pour requêtes OLAP.',
    category: 'database',
    iconUrl: null,
    docsUrl: 'https://github.com/ClickHouse/clickhouse-mcp',
    requiresApiKey: true,
    envKeyName: 'CLICKHOUSE_URL',
    tags: ['analytics', 'olap', 'columnar', 'fast'],
    popular: false,
  },

  // ── Cloud Platforms ───────────────────────────────────────────
  {
    id: 'digitalocean',
    name: 'DigitalOcean',
    slug: 'digitalocean',
    provider: 'DigitalOcean',
    description: 'Gestion de droplets, Kubernetes, databases et espaces DigitalOcean.',
    category: 'cloud',
    iconUrl: null,
    docsUrl: 'https://github.com/digitalocean/digitalocean-mcp',
    requiresApiKey: true,
    envKeyName: 'DIGITALOCEAN_TOKEN',
    tags: ['droplets', 'kubernetes', 'databases', 'spaces'],
    popular: false,
  },
  {
    id: 'flyio',
    name: 'Fly.io',
    slug: 'flyio',
    provider: 'Fly.io',
    description: 'Déploiement d\'apps à l\'edge, machines, volumes et secrets Fly.io.',
    category: 'cloud',
    iconUrl: null,
    docsUrl: 'https://github.com/superfly/flyio-mcp',
    requiresApiKey: true,
    envKeyName: 'FLY_API_TOKEN',
    tags: ['edge', 'deploy', 'machines', 'global'],
    popular: false,
  },

  // ── Cloud Storage ─────────────────────────────────────────────
  {
    id: 'google-drive',
    name: 'Google Drive',
    slug: 'google-drive',
    provider: 'Model Context Protocol',
    description: 'Recherche, lecture et gestion de fichiers et dossiers Google Drive.',
    category: 'productivity',
    iconUrl: null,
    docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/gdrive',
    requiresApiKey: true,
    envKeyName: 'GOOGLE_DRIVE_CREDENTIALS',
    tags: ['storage', 'files', 'documents', 'google'],
    popular: true,
  },
  {
    id: 'dropbox',
    name: 'Dropbox',
    slug: 'dropbox',
    provider: 'Dropbox',
    description: 'Gestion de fichiers, partages et synchronisation Dropbox.',
    category: 'productivity',
    iconUrl: null,
    docsUrl: 'https://github.com/dropbox/dropbox-mcp',
    requiresApiKey: true,
    envKeyName: 'DROPBOX_ACCESS_TOKEN',
    tags: ['storage', 'files', 'sync', 'sharing'],
    popular: false,
  },

  // ── Communication ─────────────────────────────────────────────
  {
    id: 'microsoft-teams',
    name: 'Microsoft Teams',
    slug: 'microsoft-teams',
    provider: 'Microsoft',
    description: 'Envoi de messages, gestion d\'équipes, canaux et réunions Teams.',
    category: 'productivity',
    iconUrl: null,
    docsUrl: 'https://github.com/microsoft/teams-mcp',
    requiresApiKey: true,
    envKeyName: 'TEAMS_BOT_TOKEN',
    tags: ['messaging', 'teams', 'meetings', 'microsoft'],
    popular: true,
  },

  // ── CRM & Marketing ──────────────────────────────────────────
  {
    id: 'salesforce',
    name: 'Salesforce',
    slug: 'salesforce',
    provider: 'Salesforce',
    description: 'Gestion d\'objets, SOQL, leads, opportunités et rapports Salesforce.',
    category: 'productivity',
    iconUrl: null,
    docsUrl: 'https://github.com/salesforce/salesforce-mcp',
    requiresApiKey: true,
    envKeyName: 'SALESFORCE_ACCESS_TOKEN',
    tags: ['crm', 'soql', 'leads', 'opportunities'],
    popular: true,
  },
  {
    id: 'mailchimp',
    name: 'Mailchimp',
    slug: 'mailchimp',
    provider: 'Mailchimp',
    description: 'Gestion de listes, campagnes email, templates et audiences Mailchimp.',
    category: 'productivity',
    iconUrl: null,
    docsUrl: 'https://github.com/mailchimp/mailchimp-mcp',
    requiresApiKey: true,
    envKeyName: 'MAILCHIMP_API_KEY',
    tags: ['email', 'campaigns', 'audiences', 'marketing'],
    popular: false,
  },

  // ── APM ───────────────────────────────────────────────────────
  {
    id: 'newrelic',
    name: 'New Relic',
    slug: 'newrelic',
    provider: 'New Relic',
    description: 'Observabilité full-stack : APM, infrastructure, logs et dashboards New Relic.',
    category: 'monitoring',
    iconUrl: null,
    docsUrl: 'https://github.com/newrelic/newrelic-mcp',
    requiresApiKey: true,
    envKeyName: 'NEW_RELIC_API_KEY',
    tags: ['apm', 'infrastructure', 'logs', 'dashboards'],
    popular: false,
  },

  // ── Data Science ──────────────────────────────────────────────
  {
    id: 'kaggle',
    name: 'Kaggle',
    slug: 'kaggle',
    provider: 'Google',
    description: 'Accès aux datasets, compétitions, notebooks et modèles Kaggle.',
    category: 'data',
    iconUrl: null,
    docsUrl: 'https://github.com/Kaggle/kaggle-mcp',
    requiresApiKey: true,
    envKeyName: 'KAGGLE_KEY',
    tags: ['datasets', 'competitions', 'notebooks', 'data-science'],
    popular: true,
  },
  {
    id: 'tableau',
    name: 'Tableau',
    slug: 'tableau',
    provider: 'Salesforce',
    description: 'Interaction avec workbooks, vues, dashboards et datasources Tableau.',
    category: 'data',
    iconUrl: null,
    docsUrl: 'https://github.com/tableau/tableau-mcp',
    requiresApiKey: true,
    envKeyName: 'TABLEAU_TOKEN',
    tags: ['visualization', 'dashboards', 'analytics', 'bi'],
    popular: false,
  },

  // ── Security & Code Quality ───────────────────────────────────
  {
    id: 'snyk',
    name: 'Snyk',
    slug: 'snyk',
    provider: 'Snyk',
    description: 'Scan de vulnérabilités dans le code, les dépendances, les conteneurs et l\'IaC.',
    category: 'development',
    iconUrl: null,
    docsUrl: 'https://github.com/snyk/snyk-mcp',
    requiresApiKey: true,
    envKeyName: 'SNYK_TOKEN',
    tags: ['security', 'vulnerabilities', 'dependencies', 'sca'],
    popular: true,
  },
  {
    id: 'sonarqube',
    name: 'SonarQube',
    slug: 'sonarqube',
    provider: 'SonarSource',
    description: 'Analyse de qualité de code : bugs, code smells, couverture et dette technique.',
    category: 'development',
    iconUrl: null,
    docsUrl: 'https://github.com/SonarSource/sonarqube-mcp',
    requiresApiKey: true,
    envKeyName: 'SONAR_TOKEN',
    tags: ['code-quality', 'bugs', 'coverage', 'technical-debt'],
    popular: true,
  },
  {
    id: 'raycast',
    name: 'Raycast',
    slug: 'raycast',
    provider: 'Raycast',
    description: 'Intégration avec Raycast pour extensions, commandes et productivité développeur.',
    category: 'development',
    iconUrl: null,
    docsUrl: 'https://github.com/raycast/raycast-mcp',
    requiresApiKey: true,
    envKeyName: 'RAYCAST_API_KEY',
    tags: ['launcher', 'extensions', 'productivity', 'macos'],
    popular: false,
  },
  {
    id: 'cursor',
    name: 'Cursor',
    slug: 'cursor',
    provider: 'Cursor',
    description: 'Interaction avec l\'éditeur Cursor : fichiers, terminal, recherche et refactoring IA.',
    category: 'development',
    iconUrl: null,
    docsUrl: 'https://github.com/cursor-ai/cursor-mcp',
    requiresApiKey: false,
    envKeyName: null,
    tags: ['editor', 'ai', 'refactoring', 'ide'],
    popular: true,
  },

  // ── Distributed & Serverless DBs ──────────────────────────────
  {
    id: 'tidb',
    name: 'TiDB',
    slug: 'tidb',
    provider: 'PingCAP',
    description: 'Base SQL distribuée compatible MySQL avec scalabilité horizontale.',
    category: 'database',
    iconUrl: null,
    docsUrl: 'https://github.com/pingcap/tidb-mcp',
    requiresApiKey: true,
    envKeyName: 'TIDB_HOST',
    tags: ['sql', 'distributed', 'mysql-compatible', 'htap'],
    popular: false,
  },
  {
    id: 'fauna',
    name: 'Fauna',
    slug: 'fauna',
    provider: 'Fauna',
    description: 'Base de données document-relationnelle serverless avec transactions ACID.',
    category: 'database',
    iconUrl: null,
    docsUrl: 'https://github.com/fauna/fauna-mcp',
    requiresApiKey: true,
    envKeyName: 'FAUNA_SECRET',
    tags: ['serverless', 'document', 'transactions', 'graphql'],
    popular: false,
  },
  {
    id: 'upstash',
    name: 'Upstash',
    slug: 'upstash',
    provider: 'Upstash',
    description: 'Redis et Kafka serverless avec tarification à l\'usage et edge computing.',
    category: 'database',
    iconUrl: null,
    docsUrl: 'https://github.com/upstash/upstash-mcp',
    requiresApiKey: true,
    envKeyName: 'UPSTASH_REDIS_REST_TOKEN',
    tags: ['redis', 'kafka', 'serverless', 'edge'],
    popular: false,
  },

  // ── IaC & PaaS ───────────────────────────────────────────────
  {
    id: 'pulumi',
    name: 'Pulumi',
    slug: 'pulumi',
    provider: 'Pulumi',
    description: 'Infrastructure as code en TypeScript, Python, Go et C# avec Pulumi.',
    category: 'cloud',
    iconUrl: null,
    docsUrl: 'https://github.com/pulumi/pulumi-mcp',
    requiresApiKey: true,
    envKeyName: 'PULUMI_ACCESS_TOKEN',
    tags: ['iac', 'infrastructure', 'typescript', 'multi-cloud'],
    popular: false,
  },
  {
    id: 'render',
    name: 'Render',
    slug: 'render',
    provider: 'Render',
    description: 'Déploiement de services web, bases de données et cron jobs sur Render.',
    category: 'cloud',
    iconUrl: null,
    docsUrl: 'https://github.com/render-oss/render-mcp',
    requiresApiKey: true,
    envKeyName: 'RENDER_API_KEY',
    tags: ['deploy', 'hosting', 'databases', 'cron'],
    popular: false,
  },
  {
    id: 'railway',
    name: 'Railway',
    slug: 'railway',
    provider: 'Railway',
    description: 'Déploiement d\'apps, bases de données et services avec Railway.',
    category: 'cloud',
    iconUrl: null,
    docsUrl: 'https://github.com/railwayapp/railway-mcp',
    requiresApiKey: true,
    envKeyName: 'RAILWAY_TOKEN',
    tags: ['deploy', 'hosting', 'databases', 'paas'],
    popular: false,
  },

  // ── Project & Team Management ─────────────────────────────────
  {
    id: 'trello',
    name: 'Trello',
    slug: 'trello',
    provider: 'Atlassian',
    description: 'Gestion de boards, listes, cartes et automatisation Trello.',
    category: 'productivity',
    iconUrl: null,
    docsUrl: 'https://github.com/atlassian/trello-mcp',
    requiresApiKey: true,
    envKeyName: 'TRELLO_API_KEY',
    tags: ['boards', 'cards', 'kanban', 'project-management'],
    popular: true,
  },
  {
    id: 'monday',
    name: 'Monday.com',
    slug: 'monday',
    provider: 'Monday.com',
    description: 'Gestion de boards, items, colonnes et automatisations Monday.com.',
    category: 'productivity',
    iconUrl: null,
    docsUrl: 'https://github.com/mondaycom/monday-mcp',
    requiresApiKey: true,
    envKeyName: 'MONDAY_API_TOKEN',
    tags: ['boards', 'items', 'automation', 'work-management'],
    popular: false,
  },
  {
    id: 'intercom',
    name: 'Intercom',
    slug: 'intercom',
    provider: 'Intercom',
    description: 'Messagerie client, gestion de conversations, contacts et articles Intercom.',
    category: 'productivity',
    iconUrl: null,
    docsUrl: 'https://github.com/intercom/intercom-mcp',
    requiresApiKey: true,
    envKeyName: 'INTERCOM_ACCESS_TOKEN',
    tags: ['messaging', 'support', 'conversations', 'crm'],
    popular: false,
  },
  {
    id: 'calendly',
    name: 'Calendly',
    slug: 'calendly',
    provider: 'Calendly',
    description: 'Gestion d\'événements, disponibilités et planification de rendez-vous Calendly.',
    category: 'productivity',
    iconUrl: null,
    docsUrl: 'https://github.com/calendly/calendly-mcp',
    requiresApiKey: true,
    envKeyName: 'CALENDLY_API_KEY',
    tags: ['scheduling', 'events', 'meetings', 'calendar'],
    popular: false,
  },

  // ── AI Inference & Models ─────────────────────────────────────
  {
    id: 'replicate',
    name: 'Replicate',
    slug: 'replicate',
    provider: 'Replicate',
    description: 'Exécution de modèles ML open-source dans le cloud : images, vidéos, audio.',
    category: 'ai',
    iconUrl: null,
    docsUrl: 'https://github.com/replicate/replicate-mcp',
    requiresApiKey: true,
    envKeyName: 'REPLICATE_API_TOKEN',
    tags: ['inference', 'models', 'image-generation', 'open-source'],
    popular: true,
  },
  {
    id: 'cohere',
    name: 'Cohere',
    slug: 'cohere',
    provider: 'Cohere',
    description: 'Modèles de langage pour embeddings, classification, RAG et génération.',
    category: 'ai',
    iconUrl: null,
    docsUrl: 'https://github.com/cohere-ai/cohere-mcp',
    requiresApiKey: true,
    envKeyName: 'COHERE_API_KEY',
    tags: ['llm', 'embeddings', 'classification', 'rag'],
    popular: false,
  },
  {
    id: 'mistral',
    name: 'Mistral AI',
    slug: 'mistral',
    provider: 'Mistral AI',
    description: 'Accès aux modèles Mistral, Mixtral et Codestral pour la génération et le code.',
    category: 'ai',
    iconUrl: null,
    docsUrl: 'https://github.com/mistralai/mistral-mcp',
    requiresApiKey: true,
    envKeyName: 'MISTRAL_API_KEY',
    tags: ['llm', 'mistral', 'mixtral', 'code-generation'],
    popular: true,
  },

  // ── Data Integration & ETL ────────────────────────────────────
  {
    id: 'segment',
    name: 'Segment',
    slug: 'segment',
    provider: 'Twilio Segment',
    description: 'Customer data platform : sources, destinations, tracking et profils utilisateurs.',
    category: 'data',
    iconUrl: null,
    docsUrl: 'https://github.com/segmentio/segment-mcp',
    requiresApiKey: true,
    envKeyName: 'SEGMENT_WRITE_KEY',
    tags: ['cdp', 'tracking', 'analytics', 'customer-data'],
    popular: false,
  },
  {
    id: 'airbyte',
    name: 'Airbyte',
    slug: 'airbyte',
    provider: 'Airbyte',
    description: 'Plateforme ELT open-source pour synchroniser des données entre 300+ connecteurs.',
    category: 'data',
    iconUrl: null,
    docsUrl: 'https://github.com/airbytehq/airbyte-mcp',
    requiresApiKey: true,
    envKeyName: 'AIRBYTE_API_KEY',
    tags: ['etl', 'elt', 'connectors', 'data-sync'],
    popular: false,
  },
  {
    id: 'dbt',
    name: 'dbt',
    slug: 'dbt',
    provider: 'dbt Labs',
    description: 'Transformations SQL, modèles, tests et documentation dbt pour data warehouses.',
    category: 'data',
    iconUrl: null,
    docsUrl: 'https://github.com/dbt-labs/dbt-mcp',
    requiresApiKey: true,
    envKeyName: 'DBT_API_KEY',
    tags: ['sql', 'transformations', 'models', 'data-warehouse'],
    popular: true,
  },

  // ── Media & Social ────────────────────────────────────────────
  {
    id: 'twitch',
    name: 'Twitch',
    slug: 'twitch',
    provider: 'Twitch',
    description: 'Gestion de streams, chat, clips et analytics via l\'API Twitch.',
    category: 'productivity',
    iconUrl: null,
    docsUrl: 'https://github.com/twitch/twitch-mcp',
    requiresApiKey: true,
    envKeyName: 'TWITCH_ACCESS_TOKEN',
    tags: ['streaming', 'chat', 'clips', 'gaming'],
    popular: false,
  },
  {
    id: 'spotify',
    name: 'Spotify',
    slug: 'spotify',
    provider: 'Spotify',
    description: 'Recherche de musique, gestion de playlists et contrôle de lecture Spotify.',
    category: 'productivity',
    iconUrl: null,
    docsUrl: 'https://github.com/spotify/spotify-mcp',
    requiresApiKey: true,
    envKeyName: 'SPOTIFY_CLIENT_SECRET',
    tags: ['music', 'playlists', 'playback', 'search'],
    popular: true,
  },
  {
    id: 'youtube',
    name: 'YouTube',
    slug: 'youtube',
    provider: 'Google',
    description: 'Recherche de vidéos, gestion de playlists, commentaires et analytics YouTube.',
    category: 'data',
    iconUrl: null,
    docsUrl: 'https://github.com/google/youtube-mcp',
    requiresApiKey: true,
    envKeyName: 'YOUTUBE_API_KEY',
    tags: ['videos', 'playlists', 'comments', 'analytics'],
    popular: true,
  },

  // ── Messaging Platforms ───────────────────────────────────────
  {
    id: 'whatsapp',
    name: 'WhatsApp Business',
    slug: 'whatsapp',
    provider: 'Meta',
    description: 'Envoi de messages, templates et gestion de contacts WhatsApp Business API.',
    category: 'productivity',
    iconUrl: null,
    docsUrl: 'https://github.com/nicepkg/whatsapp-mcp',
    requiresApiKey: true,
    envKeyName: 'WHATSAPP_TOKEN',
    tags: ['messaging', 'templates', 'contacts', 'business'],
    popular: true,
  },
  {
    id: 'telegram',
    name: 'Telegram',
    slug: 'telegram',
    provider: 'Telegram',
    description: 'Bots Telegram : envoi de messages, gestion de groupes et commandes.',
    category: 'productivity',
    iconUrl: null,
    docsUrl: 'https://github.com/nicepkg/telegram-mcp',
    requiresApiKey: true,
    envKeyName: 'TELEGRAM_BOT_TOKEN',
    tags: ['bots', 'messaging', 'groups', 'channels'],
    popular: false,
  },
  {
    id: 'zoom',
    name: 'Zoom',
    slug: 'zoom',
    provider: 'Zoom',
    description: 'Gestion de réunions, webinars, enregistrements et participants Zoom.',
    category: 'productivity',
    iconUrl: null,
    docsUrl: 'https://github.com/zoom/zoom-mcp',
    requiresApiKey: true,
    envKeyName: 'ZOOM_ACCOUNT_ID',
    tags: ['meetings', 'webinars', 'recordings', 'video'],
    popular: true,
  },

  // ── Git Tools & CI/CD ────────────────────────────────────────
  {
    id: 'gitkraken',
    name: 'GitKraken',
    slug: 'gitkraken',
    provider: 'GitKraken',
    description: 'Client Git visuel avec gestion de repos, branches et merge requests.',
    category: 'development',
    iconUrl: null,
    docsUrl: 'https://github.com/gitkraken/gitkraken-mcp',
    requiresApiKey: true,
    envKeyName: 'GITKRAKEN_TOKEN',
    tags: ['git', 'visual', 'branches', 'merge'],
    popular: false,
  },
  {
    id: 'jenkins',
    name: 'Jenkins',
    slug: 'jenkins',
    provider: 'Jenkins',
    description: 'Gestion de jobs, pipelines et builds Jenkins pour l\'intégration continue.',
    category: 'development',
    iconUrl: null,
    docsUrl: 'https://github.com/jenkinsci/jenkins-mcp',
    requiresApiKey: true,
    envKeyName: 'JENKINS_API_TOKEN',
    tags: ['ci-cd', 'pipelines', 'builds', 'automation'],
    popular: true,
  },
  {
    id: 'travisci',
    name: 'Travis CI',
    slug: 'travisci',
    provider: 'Travis CI',
    description: 'Intégration continue et déploiement avec Travis CI.',
    category: 'development',
    iconUrl: null,
    docsUrl: 'https://github.com/travis-ci/travis-mcp',
    requiresApiKey: true,
    envKeyName: 'TRAVIS_API_TOKEN',
    tags: ['ci-cd', 'builds', 'testing', 'deploy'],
    popular: false,
  },
  {
    id: 'github-actions',
    name: 'GitHub Actions',
    slug: 'github-actions',
    provider: 'GitHub',
    description: 'Gestion de workflows, runs et artifacts GitHub Actions.',
    category: 'development',
    iconUrl: null,
    docsUrl: 'https://github.com/github/actions-mcp',
    requiresApiKey: true,
    envKeyName: 'GITHUB_TOKEN',
    tags: ['ci-cd', 'workflows', 'runs', 'automation'],
    popular: true,
  },

  // ── Serverless Functions ──────────────────────────────────────
  {
    id: 'aws-lambda',
    name: 'AWS Lambda',
    slug: 'aws-lambda',
    provider: 'AWS',
    description: 'Gestion de fonctions Lambda : déploiement, invocation, logs et layers.',
    category: 'cloud',
    iconUrl: null,
    docsUrl: 'https://github.com/awslabs/lambda-mcp',
    requiresApiKey: true,
    envKeyName: 'AWS_ACCESS_KEY_ID',
    tags: ['serverless', 'functions', 'lambda', 'aws'],
    popular: true,
  },
  {
    id: 'google-cloud-run',
    name: 'Google Cloud Run',
    slug: 'google-cloud-run',
    provider: 'Google Cloud',
    description: 'Déploiement et gestion de services conteneurisés sur Cloud Run.',
    category: 'cloud',
    iconUrl: null,
    docsUrl: 'https://github.com/google-cloud/cloud-run-mcp',
    requiresApiKey: true,
    envKeyName: 'GOOGLE_APPLICATION_CREDENTIALS',
    tags: ['serverless', 'containers', 'deploy', 'google-cloud'],
    popular: false,
  },
  {
    id: 'azure-functions',
    name: 'Azure Functions',
    slug: 'azure-functions',
    provider: 'Microsoft Azure',
    description: 'Gestion de fonctions serverless Azure : déploiement, triggers et bindings.',
    category: 'cloud',
    iconUrl: null,
    docsUrl: 'https://github.com/Azure/azure-functions-mcp',
    requiresApiKey: true,
    envKeyName: 'AZURE_FUNCTIONS_KEY',
    tags: ['serverless', 'functions', 'triggers', 'azure'],
    popular: false,
  },

  // ── European Cloud ────────────────────────────────────────────
  {
    id: 'ovhcloud',
    name: 'OVHcloud',
    slug: 'ovhcloud',
    provider: 'OVHcloud',
    description: 'Gestion de serveurs, instances cloud et stockage OVHcloud.',
    category: 'cloud',
    iconUrl: null,
    docsUrl: 'https://github.com/ovh/ovhcloud-mcp',
    requiresApiKey: true,
    envKeyName: 'OVH_APPLICATION_KEY',
    tags: ['cloud', 'servers', 'storage', 'european'],
    popular: false,
  },
  {
    id: 'linode',
    name: 'Linode (Akamai)',
    slug: 'linode',
    provider: 'Akamai',
    description: 'Gestion de Linodes, volumes, NodeBalancers et Kubernetes Akamai Cloud.',
    category: 'cloud',
    iconUrl: null,
    docsUrl: 'https://github.com/linode/linode-mcp',
    requiresApiKey: true,
    envKeyName: 'LINODE_TOKEN',
    tags: ['cloud', 'linodes', 'kubernetes', 'akamai'],
    popular: false,
  },

  // ── Relational Databases ──────────────────────────────────────
  {
    id: 'mysql',
    name: 'MySQL',
    slug: 'mysql',
    provider: 'Model Context Protocol',
    description: 'Connexion et requêtes SQL sur bases MySQL et MariaDB.',
    category: 'database',
    iconUrl: null,
    docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/mysql',
    requiresApiKey: true,
    envKeyName: 'MYSQL_URL',
    tags: ['sql', 'relational', 'queries', 'mysql'],
    popular: true,
  },
  {
    id: 'postgres',
    name: 'PostgreSQL',
    slug: 'postgres',
    provider: 'Model Context Protocol',
    description: 'Connexion et requêtes SQL sur bases PostgreSQL avec introspection de schéma.',
    category: 'database',
    iconUrl: null,
    docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/postgres',
    requiresApiKey: true,
    envKeyName: 'POSTGRES_URL',
    tags: ['sql', 'relational', 'queries', 'postgres'],
    popular: true,
  },
  {
    id: 'sqlite',
    name: 'SQLite',
    slug: 'sqlite',
    provider: 'Model Context Protocol',
    description: 'Requêtes SQL sur bases SQLite locales avec lecture et écriture.',
    category: 'database',
    iconUrl: null,
    docsUrl: 'https://github.com/modelcontextprotocol/servers/tree/main/src/sqlite',
    requiresApiKey: false,
    envKeyName: null,
    tags: ['sql', 'local', 'embedded', 'lightweight'],
    popular: true,
  },
  {
    id: 'mariadb',
    name: 'MariaDB',
    slug: 'mariadb',
    provider: 'MariaDB',
    description: 'Connexion et requêtes sur bases MariaDB, fork communautaire de MySQL.',
    category: 'database',
    iconUrl: null,
    docsUrl: 'https://github.com/mariadb/mariadb-mcp',
    requiresApiKey: true,
    envKeyName: 'MARIADB_URL',
    tags: ['sql', 'relational', 'mysql-fork', 'open-source'],
    popular: false,
  },

  // ── Graph Database ────────────────────────────────────────────
  {
    id: 'neo4j',
    name: 'Neo4j',
    slug: 'neo4j',
    provider: 'Neo4j',
    description: 'Base graphe Neo4j : requêtes Cypher, noeuds, relations et traversals.',
    category: 'database',
    iconUrl: null,
    docsUrl: 'https://github.com/neo4j/neo4j-mcp',
    requiresApiKey: true,
    envKeyName: 'NEO4J_URI',
    tags: ['graph', 'cypher', 'nodes', 'relationships'],
    popular: true,
  },

  // ── Vector Databases (additional) ─────────────────────────────
  {
    id: 'qdrant',
    name: 'Qdrant',
    slug: 'qdrant',
    provider: 'Qdrant',
    description: 'Base vectorielle open-source haute performance pour la recherche de similarité.',
    category: 'ai',
    iconUrl: null,
    docsUrl: 'https://github.com/qdrant/qdrant-mcp',
    requiresApiKey: true,
    envKeyName: 'QDRANT_API_KEY',
    tags: ['vectors', 'similarity', 'open-source', 'high-performance'],
    popular: true,
  },
  {
    id: 'chroma',
    name: 'Chroma',
    slug: 'chroma',
    provider: 'Chroma',
    description: 'Base vectorielle embeddings-first pour applications IA et RAG.',
    category: 'ai',
    iconUrl: null,
    docsUrl: 'https://github.com/chroma-core/chroma-mcp',
    requiresApiKey: false,
    envKeyName: null,
    tags: ['vectors', 'embeddings', 'rag', 'open-source'],
    popular: true,
  },
  {
    id: 'milvus',
    name: 'Milvus',
    slug: 'milvus',
    provider: 'Zilliz',
    description: 'Base vectorielle distribuée pour la recherche de similarité à grande échelle.',
    category: 'ai',
    iconUrl: null,
    docsUrl: 'https://github.com/milvus-io/milvus-mcp',
    requiresApiKey: true,
    envKeyName: 'MILVUS_URI',
    tags: ['vectors', 'distributed', 'similarity', 'scale'],
    popular: false,
  },

  // ── AI Frameworks ─────────────────────────────────────────────
  {
    id: 'langchain',
    name: 'LangChain',
    slug: 'langchain',
    provider: 'LangChain',
    description: 'Framework pour chaînes LLM, agents, mémoire et outils LangChain.',
    category: 'ai',
    iconUrl: null,
    docsUrl: 'https://github.com/langchain-ai/langchain-mcp',
    requiresApiKey: false,
    envKeyName: null,
    tags: ['llm', 'agents', 'chains', 'framework'],
    popular: true,
  },
  {
    id: 'llamaindex',
    name: 'LlamaIndex',
    slug: 'llamaindex',
    provider: 'LlamaIndex',
    description: 'Framework de data ingestion et retrieval pour applications RAG.',
    category: 'ai',
    iconUrl: null,
    docsUrl: 'https://github.com/run-llama/llamaindex-mcp',
    requiresApiKey: false,
    envKeyName: null,
    tags: ['rag', 'retrieval', 'ingestion', 'framework'],
    popular: true,
  },

  // ── HashiCorp Suite ───────────────────────────────────────────
  {
    id: 'vault',
    name: 'HashiCorp Vault',
    slug: 'vault',
    provider: 'HashiCorp',
    description: 'Gestion de secrets, chiffrement et contrôle d\'accès avec Vault.',
    category: 'cloud',
    iconUrl: null,
    docsUrl: 'https://github.com/hashicorp/vault-mcp',
    requiresApiKey: true,
    envKeyName: 'VAULT_TOKEN',
    tags: ['secrets', 'encryption', 'access-control', 'security'],
    popular: true,
  },
  {
    id: 'consul',
    name: 'HashiCorp Consul',
    slug: 'consul',
    provider: 'HashiCorp',
    description: 'Service discovery, configuration et mesh réseau avec Consul.',
    category: 'cloud',
    iconUrl: null,
    docsUrl: 'https://github.com/hashicorp/consul-mcp',
    requiresApiKey: true,
    envKeyName: 'CONSUL_HTTP_TOKEN',
    tags: ['service-discovery', 'mesh', 'configuration', 'networking'],
    popular: false,
  },
  {
    id: 'packer',
    name: 'HashiCorp Packer',
    slug: 'packer',
    provider: 'HashiCorp',
    description: 'Création d\'images machine automatisées pour le multi-cloud avec Packer.',
    category: 'cloud',
    iconUrl: null,
    docsUrl: 'https://github.com/hashicorp/packer-mcp',
    requiresApiKey: false,
    envKeyName: null,
    tags: ['images', 'ami', 'automation', 'multi-cloud'],
    popular: false,
  },
  {
    id: 'ansible',
    name: 'Ansible',
    slug: 'ansible',
    provider: 'Red Hat',
    description: 'Automatisation IT : playbooks, inventaires et rôles Ansible.',
    category: 'cloud',
    iconUrl: null,
    docsUrl: 'https://github.com/ansible/ansible-mcp',
    requiresApiKey: false,
    envKeyName: null,
    tags: ['automation', 'playbooks', 'configuration', 'devops'],
    popular: true,
  },

  // ── Observability Stack ───────────────────────────────────────
  {
    id: 'prometheus',
    name: 'Prometheus',
    slug: 'prometheus',
    provider: 'CNCF',
    description: 'Requêtes PromQL, alertes et exploration de métriques Prometheus.',
    category: 'monitoring',
    iconUrl: null,
    docsUrl: 'https://github.com/prometheus/prometheus-mcp',
    requiresApiKey: true,
    envKeyName: 'PROMETHEUS_URL',
    tags: ['metrics', 'promql', 'alerts', 'time-series'],
    popular: true,
  },
  {
    id: 'loki',
    name: 'Grafana Loki',
    slug: 'loki',
    provider: 'Grafana',
    description: 'Agrégation et recherche de logs avec Loki et LogQL.',
    category: 'monitoring',
    iconUrl: null,
    docsUrl: 'https://github.com/grafana/loki-mcp',
    requiresApiKey: true,
    envKeyName: 'LOKI_URL',
    tags: ['logs', 'logql', 'aggregation', 'grafana'],
    popular: false,
  },
  {
    id: 'tempo',
    name: 'Grafana Tempo',
    slug: 'tempo',
    provider: 'Grafana',
    description: 'Traçage distribué avec Tempo : traces, spans et service maps.',
    category: 'monitoring',
    iconUrl: null,
    docsUrl: 'https://github.com/grafana/tempo-mcp',
    requiresApiKey: true,
    envKeyName: 'TEMPO_URL',
    tags: ['tracing', 'spans', 'distributed', 'grafana'],
    popular: false,
  },

  // ── Browser & Testing ─────────────────────────────────────────
  {
    id: 'puppeteer-browser',
    name: 'Puppeteer',
    slug: 'puppeteer-browser',
    provider: 'Google',
    description: 'Automatisation de navigateur headless Chrome avec Puppeteer.',
    category: 'development',
    iconUrl: null,
    docsUrl: 'https://github.com/nicepkg/puppeteer-mcp',
    requiresApiKey: false,
    envKeyName: null,
    tags: ['browser', 'headless', 'automation', 'chrome'],
    popular: true,
  },
  {
    id: 'selenium',
    name: 'Selenium',
    slug: 'selenium',
    provider: 'Selenium',
    description: 'Tests automatisés multi-navigateurs avec Selenium WebDriver.',
    category: 'development',
    iconUrl: null,
    docsUrl: 'https://github.com/nicepkg/selenium-mcp',
    requiresApiKey: false,
    envKeyName: null,
    tags: ['testing', 'browser', 'webdriver', 'automation'],
    popular: false,
  },
  {
    id: 'cypress',
    name: 'Cypress',
    slug: 'cypress',
    provider: 'Cypress',
    description: 'Tests end-to-end rapides pour applications web avec Cypress.',
    category: 'development',
    iconUrl: null,
    docsUrl: 'https://github.com/cypress-io/cypress-mcp',
    requiresApiKey: true,
    envKeyName: 'CYPRESS_RECORD_KEY',
    tags: ['e2e', 'testing', 'frontend', 'automation'],
    popular: true,
  },

  // ── UI & Documentation ────────────────────────────────────────
  {
    id: 'storybook',
    name: 'Storybook',
    slug: 'storybook',
    provider: 'Storybook',
    description: 'Développement et documentation de composants UI isolés avec Storybook.',
    category: 'development',
    iconUrl: null,
    docsUrl: 'https://github.com/storybookjs/storybook-mcp',
    requiresApiKey: false,
    envKeyName: null,
    tags: ['ui', 'components', 'documentation', 'design-system'],
    popular: true,
  },
  {
    id: 'chromatic',
    name: 'Chromatic',
    slug: 'chromatic',
    provider: 'Chromatic',
    description: 'Tests visuels et revue UI automatisés pour Storybook avec Chromatic.',
    category: 'development',
    iconUrl: null,
    docsUrl: 'https://github.com/chromaui/chromatic-mcp',
    requiresApiKey: true,
    envKeyName: 'CHROMATIC_PROJECT_TOKEN',
    tags: ['visual-testing', 'ui-review', 'storybook', 'screenshots'],
    popular: false,
  },
  {
    id: 'docusaurus',
    name: 'Docusaurus',
    slug: 'docusaurus',
    provider: 'Meta',
    description: 'Création et gestion de sites de documentation avec Docusaurus.',
    category: 'development',
    iconUrl: null,
    docsUrl: 'https://github.com/facebook/docusaurus-mcp',
    requiresApiKey: false,
    envKeyName: null,
    tags: ['documentation', 'static-site', 'markdown', 'react'],
    popular: false,
  },
  {
    id: 'mintlify',
    name: 'Mintlify',
    slug: 'mintlify',
    provider: 'Mintlify',
    description: 'Documentation API moderne avec Mintlify : MDX, composants interactifs.',
    category: 'development',
    iconUrl: null,
    docsUrl: 'https://github.com/mintlify/mintlify-mcp',
    requiresApiKey: true,
    envKeyName: 'MINTLIFY_API_KEY',
    tags: ['documentation', 'api-docs', 'mdx', 'interactive'],
    popular: false,
  },
  {
    id: 'readme',
    name: 'ReadMe',
    slug: 'readme',
    provider: 'ReadMe',
    description: 'Hub de documentation API avec try-it, changelogs et analytics ReadMe.',
    category: 'development',
    iconUrl: null,
    docsUrl: 'https://github.com/readmeio/readme-mcp',
    requiresApiKey: true,
    envKeyName: 'README_API_KEY',
    tags: ['api-docs', 'changelogs', 'developer-hub', 'analytics'],
    popular: false,
  },

  // ── Payment & Fintech ─────────────────────────────────────────
  {
    id: 'paypal',
    name: 'PayPal',
    slug: 'paypal',
    provider: 'PayPal',
    description: 'Paiements, commandes, abonnements et factures via l\'API PayPal.',
    category: 'productivity',
    iconUrl: null,
    docsUrl: 'https://github.com/nicepkg/paypal-mcp',
    requiresApiKey: true,
    envKeyName: 'PAYPAL_CLIENT_SECRET',
    tags: ['payments', 'orders', 'subscriptions', 'invoices'],
    popular: true,
  },
  {
    id: 'square',
    name: 'Square',
    slug: 'square',
    provider: 'Square',
    description: 'Paiements, catalogue produits et gestion clients Square.',
    category: 'productivity',
    iconUrl: null,
    docsUrl: 'https://github.com/square/square-mcp',
    requiresApiKey: true,
    envKeyName: 'SQUARE_ACCESS_TOKEN',
    tags: ['payments', 'catalog', 'customers', 'pos'],
    popular: false,
  },
  {
    id: 'plaid',
    name: 'Plaid',
    slug: 'plaid',
    provider: 'Plaid',
    description: 'Connexion bancaire, transactions, soldes et vérification d\'identité Plaid.',
    category: 'data',
    iconUrl: null,
    docsUrl: 'https://github.com/plaid/plaid-mcp',
    requiresApiKey: true,
    envKeyName: 'PLAID_SECRET',
    tags: ['banking', 'transactions', 'identity', 'fintech'],
    popular: false,
  },

  // ── Auth & Identity ───────────────────────────────────────────
  {
    id: 'auth0',
    name: 'Auth0',
    slug: 'auth0',
    provider: 'Okta (Auth0)',
    description: 'Gestion d\'utilisateurs, rôles, connexions et règles Auth0.',
    category: 'cloud',
    iconUrl: null,
    docsUrl: 'https://github.com/auth0/auth0-mcp',
    requiresApiKey: true,
    envKeyName: 'AUTH0_MANAGEMENT_TOKEN',
    tags: ['auth', 'users', 'roles', 'sso'],
    popular: true,
  },
  {
    id: 'okta',
    name: 'Okta',
    slug: 'okta',
    provider: 'Okta',
    description: 'Gestion d\'identités, applications, groupes et politiques Okta.',
    category: 'cloud',
    iconUrl: null,
    docsUrl: 'https://github.com/okta/okta-mcp',
    requiresApiKey: true,
    envKeyName: 'OKTA_API_TOKEN',
    tags: ['identity', 'sso', 'groups', 'policies'],
    popular: false,
  },
  {
    id: 'clerk',
    name: 'Clerk',
    slug: 'clerk',
    provider: 'Clerk',
    description: 'Auth et gestion d\'utilisateurs pour apps Next.js, React et JavaScript.',
    category: 'cloud',
    iconUrl: null,
    docsUrl: 'https://github.com/clerk/clerk-mcp',
    requiresApiKey: true,
    envKeyName: 'CLERK_SECRET_KEY',
    tags: ['auth', 'users', 'nextjs', 'react'],
    popular: true,
  },

  // ── Email & Notifications ─────────────────────────────────────
  {
    id: 'resend',
    name: 'Resend',
    slug: 'resend',
    provider: 'Resend',
    description: 'Envoi d\'emails transactionnels avec React Email et API moderne Resend.',
    category: 'productivity',
    iconUrl: null,
    docsUrl: 'https://github.com/resend/resend-mcp',
    requiresApiKey: true,
    envKeyName: 'RESEND_API_KEY',
    tags: ['email', 'transactional', 'react-email', 'api'],
    popular: true,
  },
  {
    id: 'novu',
    name: 'Novu',
    slug: 'novu',
    provider: 'Novu',
    description: 'Infrastructure de notifications multi-canal : email, SMS, push, in-app.',
    category: 'productivity',
    iconUrl: null,
    docsUrl: 'https://github.com/novuhq/novu-mcp',
    requiresApiKey: true,
    envKeyName: 'NOVU_API_KEY',
    tags: ['notifications', 'multi-channel', 'push', 'in-app'],
    popular: false,
  },

  // ── Real-time Analytics ───────────────────────────────────────
  {
    id: 'tinybird',
    name: 'Tinybird',
    slug: 'tinybird',
    provider: 'Tinybird',
    description: 'Analytics temps réel sur des données de streaming avec SQL et API endpoints.',
    category: 'data',
    iconUrl: null,
    docsUrl: 'https://github.com/tinybirdco/tinybird-mcp',
    requiresApiKey: true,
    envKeyName: 'TINYBIRD_TOKEN',
    tags: ['real-time', 'analytics', 'streaming', 'sql-api'],
    popular: false,
  },
  {
    id: 'motherduck',
    name: 'MotherDuck',
    slug: 'motherduck',
    provider: 'MotherDuck',
    description: 'DuckDB serverless dans le cloud : requêtes analytiques SQL ultra-rapides.',
    category: 'data',
    iconUrl: null,
    docsUrl: 'https://github.com/motherduck-io/motherduck-mcp',
    requiresApiKey: true,
    envKeyName: 'MOTHERDUCK_TOKEN',
    tags: ['duckdb', 'serverless', 'analytics', 'sql'],
    popular: false,
  },
];

// ─── Lookup Helpers ─────────────────────────────────────────────

const CATALOG_MAP = new Map(MCP_TOOLS_CATALOG.map(t => [t.id, t]));

export function getToolById(id: string): McpToolDefinition | undefined {
  return CATALOG_MAP.get(id);
}

export function getToolsByCategory(category: McpToolCategory): McpToolDefinition[] {
  return MCP_TOOLS_CATALOG.filter(t => t.category === category);
}

export function getPopularTools(): McpToolDefinition[] {
  return MCP_TOOLS_CATALOG.filter(t => t.popular);
}

export function searchTools(query: string): McpToolDefinition[] {
  const q = query.slice(0, 200).toLowerCase().trim();
  if (!q) return MCP_TOOLS_CATALOG;
  return MCP_TOOLS_CATALOG.filter(
    t =>
      t.name.toLowerCase().includes(q) ||
      t.description.toLowerCase().includes(q) ||
      t.provider.toLowerCase().includes(q) ||
      t.tags.some(tag => tag.includes(q))
  );
}
