// Seed list of popular libraries to ingest first. Extend as needed.
export interface Seed {
  owner: string;
  repo: string;
}

export const SEED_LIBRARIES: Seed[] = [
  { owner: "vercel", repo: "next.js" },
  { owner: "facebook", repo: "react" },
  { owner: "vuejs", repo: "core" },
  { owner: "sveltejs", repo: "svelte" },
  { owner: "solidjs", repo: "solid" },
  { owner: "angular", repo: "angular" },
  { owner: "remix-run", repo: "remix" },
  { owner: "nuxt", repo: "nuxt" },
  { owner: "withastro", repo: "astro" },
  { owner: "tailwindlabs", repo: "tailwindcss" },
  { owner: "shadcn-ui", repo: "ui" },
  { owner: "TanStack", repo: "query" },
  { owner: "TanStack", repo: "router" },
  { owner: "pmndrs", repo: "zustand" },
  { owner: "reduxjs", repo: "redux" },
  { owner: "reduxjs", repo: "redux-toolkit" },
  { owner: "colinhacks", repo: "zod" },
  { owner: "trpc", repo: "trpc" },
  { owner: "prisma", repo: "prisma" },
  { owner: "drizzle-team", repo: "drizzle-orm" },
  { owner: "nestjs", repo: "nest" },
  { owner: "expressjs", repo: "express" },
  { owner: "fastify", repo: "fastify" },
  { owner: "honojs", repo: "hono" },
  { owner: "nodejs", repo: "node" },
  { owner: "microsoft", repo: "TypeScript" },
  { owner: "django", repo: "django" },
  { owner: "pallets", repo: "flask" },
  { owner: "tiangolo", repo: "fastapi" },
  { owner: "python", repo: "cpython" },
  { owner: "pandas-dev", repo: "pandas" },
  { owner: "numpy", repo: "numpy" },
  { owner: "pytorch", repo: "pytorch" },
  { owner: "huggingface", repo: "transformers" },
  { owner: "langchain-ai", repo: "langchain" },
  { owner: "openai", repo: "openai-python" },
  { owner: "anthropics", repo: "anthropic-sdk-python" },
  { owner: "rust-lang", repo: "rust" },
  { owner: "tokio-rs", repo: "tokio" },
  { owner: "serde-rs", repo: "serde" },
  { owner: "golang", repo: "go" },
  { owner: "gin-gonic", repo: "gin" },
  { owner: "laravel", repo: "laravel" },
  { owner: "symfony", repo: "symfony" },
  { owner: "rails", repo: "rails" },
  { owner: "supabase", repo: "supabase" },
  { owner: "firebase", repo: "firebase-js-sdk" },
  { owner: "stripe", repo: "stripe-node" },
  { owner: "modelcontextprotocol", repo: "typescript-sdk" },
  { owner: "modelcontextprotocol", repo: "python-sdk" },
];
