import type { Metadata } from "next";
import Link from "next/link";
import type { Route } from "next";

export const metadata: Metadata = {
  title: "Privacy Policy",
  description: "How TwinMCP collects, uses, and protects your personal data. GDPR compliant.",
  alternates: {
    canonical: "/legal/en/privacy",
    languages: { en: "/legal/en/privacy", fr: "/legal/privacy" },
  },
  robots: { index: true, follow: true },
};

const LAST_UPDATED = "September 20, 2026";

export default function PrivacyPageEn() {
  return (
    <article className="mx-auto max-w-3xl px-6 py-16 lg:px-10 lg:py-24">
      <header className="mb-12 border-b border-border/60 pb-8">
        <p className="flex items-center justify-between gap-4 text-xs uppercase tracking-wider text-muted-foreground">
          <span>Legal document</span>
          <Link
            href={"/legal/privacy" as Route}
            className="normal-case underline hover:text-foreground"
          >
            Français
          </Link>
        </p>
        <h1 className="mt-3 text-4xl font-semibold tracking-tight">Privacy Policy</h1>
        <p className="mt-3 text-sm text-muted-foreground">Last updated: {LAST_UPDATED}</p>
      </header>

      <div className="prose prose-neutral dark:prose-invert max-w-none [&_h2]:mt-12 [&_h2]:text-xl [&_h2]:font-semibold [&_h2]:tracking-tight [&_h3]:mt-6 [&_h3]:text-base [&_h3]:font-semibold [&_p]:text-sm [&_p]:leading-relaxed [&_p]:text-muted-foreground [&_li]:text-sm [&_li]:text-muted-foreground [&_table]:text-sm [&_th]:font-medium [&_th]:text-foreground [&_td]:text-muted-foreground">
        <section>
          <p>
            This is an English translation provided for convenience. The{" "}
            <Link href={"/legal/privacy" as Route}>French version</Link> is the authoritative text
            and prevails in case of any discrepancy.
          </p>
          <p>
            This policy explains what data TwinMCP collects, why, who it is shared with, and how to
            exercise your rights. It applies to the twinmcp.fr site, its APIs, and the hosted MCP
            server runtime service.
          </p>
        </section>

        <h2>1. Data controller</h2>
        <p>
          The data controller is the publisher of TwinMCP, whose full identity (name, legal form,
          address, company registration) is set out in the{" "}
          <Link href={"/legal/en/notice" as Route}>legal notice</Link>. It can be reached at{" "}
          <a href="mailto:hello@twinmcp.fr">hello@twinmcp.fr</a>.
        </p>

        <h2>2. Data we collect</h2>
        <h3>2.1 Account and authentication</h3>
        <ul>
          <li>Email address (required)</li>
          <li>Password (hashed, never stored in clear) or OAuth identifier (GitHub, Google)</li>
          <li>Unique user ID generated by Supabase Auth</li>
          <li>Account creation date, last sign-in date</li>
        </ul>

        <h3>2.2 Billing</h3>
        <ul>
          <li>
            Payment details (card, IBAN): processed and stored by Stripe. We never see full card
            numbers.
          </li>
          <li>Plan, billing history, Stripe identifiers (customer, subscription)</li>
          <li>Billing address and VAT number if provided</li>
        </ul>

        <h3>2.3 Service usage</h3>
        <ul>
          <li>MCP servers created, MCPs installed, associated configurations</li>
          <li>API request audit logs (method, route, status code, timestamp, key identifier)</li>
          <li>
            Request IP address: recorded in the audit logs (which you can view in your dashboard)
            for security and abuse detection. Rate-limiting, in contrast, is applied per account,
            not per IP.
          </li>
        </ul>

        <h3>2.4 Analytics and monitoring</h3>
        <ul>
          <li>
            Product events (PostHog): page views, clicks on the main buttons, sign-up funnel steps
          </li>
          <li>Application errors (Sentry): stack traces, browser, URL</li>
          <li>Infrastructure metrics (Axiom): latency, HTTP codes, throughput</li>
        </ul>

        <h2>3. Why we process this data</h2>
        <table>
          <thead>
            <tr>
              <th>Purpose</th>
              <th>Legal basis (GDPR art. 6)</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Providing the service (account, MCP runtime)</td>
              <td>Performance of the contract</td>
            </tr>
            <tr>
              <td>Billing and payment</td>
              <td>Performance of the contract + legal obligation (accounting)</td>
            </tr>
            <tr>
              <td>Security, anti-abuse, rate-limiting</td>
              <td>Legitimate interest</td>
            </tr>
            <tr>
              <td>Product analytics, service improvement</td>
              <td>Legitimate interest (anonymized) / Consent</td>
            </tr>
            <tr>
              <td>Transactional emails (confirmation, alerts)</td>
              <td>Performance of the contract</td>
            </tr>
            <tr>
              <td>Newsletter or marketing emails</td>
              <td>Consent (opt-in, unsubscribe at any time)</td>
            </tr>
          </tbody>
        </table>

        <h2>4. Who we share with</h2>
        <p>
          We have never sold and will never sell your data. It is shared only with the technical
          sub-processors needed to operate the service:
        </p>
        <table>
          <thead>
            <tr>
              <th>Sub-processor</th>
              <th>Role</th>
              <th>Location</th>
            </tr>
          </thead>
          <tbody>
            <tr>
              <td>Supabase</td>
              <td>Database, authentication</td>
              <td>EU / US (depending on chosen region)</td>
            </tr>
            <tr>
              <td>Stripe</td>
              <td>Payment processing</td>
              <td>EU / US</td>
            </tr>
            <tr>
              <td>Upstash</td>
              <td>Cache, rate-limiting, task queue</td>
              <td>EU / US</td>
            </tr>
            <tr>
              <td>OpenAI</td>
              <td>Generating embeddings for document indexing and search</td>
              <td>United States</td>
            </tr>
            <tr>
              <td>Resend</td>
              <td>Sending transactional emails</td>
              <td>EU</td>
            </tr>
            <tr>
              <td>Sentry</td>
              <td>Error monitoring (no cookie, no session recording)</td>
              <td>EU</td>
            </tr>
            <tr>
              <td>PostHog</td>
              <td>Product analytics</td>
              <td>EU (EU region)</td>
            </tr>
            <tr>
              <td>Axiom</td>
              <td>Infrastructure logs</td>
              <td>EU</td>
            </tr>
            <tr>
              <td>Site host</td>
              <td>Hosting of the application server (full identity in the legal notice)</td>
              <td>EU</td>
            </tr>
          </tbody>
        </table>
        <p>
          Where a transfer outside the EU is necessary, it is governed by the Standard Contractual
          Clauses (SCCs) approved by the European Commission.
        </p>

        <h2>5. Retention</h2>
        <ul>
          <li>
            <strong>Active account:</strong> for as long as the account exists.
          </li>
          <li>
            <strong>Account deletion:</strong> immediate — account, servers, keys, and
            authentication identity are deleted. Audit logs kept for security and our legal
            obligations are anonymized (user identifier and IP address removed).
          </li>
          <li>
            <strong>Billing data:</strong> 10 years (French accounting obligation).
          </li>
          <li>
            <strong>Technical logs:</strong> 90 days.
          </li>
          <li>
            <strong>Analytics cookies:</strong> 13 months maximum.
          </li>
        </ul>

        <h2>6. Cookies</h2>
        <p>We use a minimal number of cookies:</p>
        <ul>
          <li>
            <strong>Supabase session</strong> (essential): keeps you signed in.
          </li>
          <li>
            <strong>PostHog</strong> (analytics): set only after your consent.
          </li>
          <li>
            <strong>Preferences</strong> (light/dark theme, language): stored in localStorage, never
            sent to the server.
          </li>
        </ul>

        <h2>7. Your rights (GDPR)</h2>
        <p>Under the General Data Protection Regulation, you have the following rights:</p>
        <ul>
          <li>
            <strong>Access:</strong> receive a copy of your data.
          </li>
          <li>
            <strong>Rectification:</strong> correct inaccurate data.
          </li>
          <li>
            <strong>Erasure:</strong> request deletion (&quot;right to be forgotten&quot;).
          </li>
          <li>
            <strong>Portability:</strong> receive your data in a structured format.
          </li>
          <li>
            <strong>Objection:</strong> object to processing based on our legitimate interest.
          </li>
          <li>
            <strong>Restriction:</strong> temporarily restrict processing.
          </li>
          <li>
            <strong>Complaint:</strong> lodge a complaint with the CNIL (French supervisory
            authority).
          </li>
        </ul>
        <p>
          You can exercise your right to erasure directly from{" "}
          <strong>Settings → Delete account</strong>: this deletes your account, servers, keys, and
          authentication identity, and anonymizes your audit logs. For the other rights (access,
          portability, rectification, objection, restriction), write to{" "}
          <a href="mailto:hello@twinmcp.fr">hello@twinmcp.fr</a> — we respond within 30 days.
        </p>

        <h2>8. Security</h2>
        <p>
          We apply industry-standard technical and organizational measures: TLS encryption in
          transit, encryption at rest, password hashing (bcrypt via Supabase), Postgres RLS
          isolation, audit logs, and least-privilege access control.
        </p>
        <p>
          In the event of a data breach likely to result in a high risk to your rights and freedoms,
          we will notify you without undue delay (GDPR art. 34) and inform the CNIL within 72 hours
          (GDPR art. 33).
        </p>

        <h2>9. Minors</h2>
        <p>
          The service is not intended for minors. In France, processing the data of a child under 15
          requires the consent of a holder of parental authority (art. 45 of the French Data
          Protection Act). We do not knowingly collect data concerning children under 15; if you
          believe this is the case, contact us for immediate deletion.
        </p>

        <h2>10. Changes to this policy</h2>
        <p>
          This policy may change. Material changes are notified by email at least 30 days before
          they take effect. A version history is available on request.
        </p>

        <h2>11. Contact</h2>
        <p>
          Any question about this policy: <a href="mailto:hello@twinmcp.fr">hello@twinmcp.fr</a>.
        </p>
      </div>

      <footer className="mt-16 border-t border-border/60 pt-6 text-xs text-muted-foreground">
        <Link href={"/legal/en/terms" as Route} className="hover:text-foreground">
          ← Terms of Service
        </Link>
      </footer>
    </article>
  );
}
